### ISSUE TITLE
Avoid defining superglobals

### ISSUE THREAD

**Issue by Ocramius** [TazeTSchnitzel/escapes#1]
- [`applyCaseBitmask()`](https://github.com/TazeTSchnitzel/escapes/blob/bda6d81553b9628959a2cf1de9aaf415bb6e3f74/src.php#L3) can be defined as a closure and unset at the end of execution of `src.php`
- [`$e`](https://github.com/TazeTSchnitzel/escapes/blob/bda6d81553b9628959a2cf1de9aaf415bb6e3f74/src.php#L12) should probably be used in the context of `array_map` to avoid overwriting any other vars
- [`$i`](https://github.com/TazeTSchnitzel/escapes/blob/bda6d81553b9628959a2cf1de9aaf415bb6e3f74/src.php#L15) same goes for any `$i` and variables defined in that block

**Comment by hikari-no-yume** [comment]
Fair point. I could namespace everything and put it into functions, since all the constants themselves are done with define(), give me a few minutes.

**Comment by hikari-no-yume** [comment]
Fixed: https://github.com/TazeTSchnitzel/escapes/commit/41832231bf1c94ec7cec51be6e17cf14962bb856

Should've put `(fixes #1)` in the commit message, but oh well.

**Comment by Ocramius** [comment]
:+1:
